import { PLATFORM_GRADIENTS, PLATFORM_EMOJIS, NICHE_EMOJIS } from "./utils";

export interface Listing {
  id: string;
  platform: string;
  username: string;
  niche: string;
  followers: number;
  monthly_income: number;
  engagement_rate: number;
  price: number;
  minimum_offer: number;
  status: "active" | "pending" | "sold";
  verified_income: boolean;
  tiktok_shop_eligible: boolean;
  monetized: boolean;
  location: string;
  description: string;
  seller_name: string;
  seller_country: string;
  seller_flag: string;
  seller_id: string;
  seller_rating: number;
  seller_sales: number;
  created_at: string;
  featured: boolean;
  isSeed?: boolean;
  listingStatus?: "active" | "pending_verification" | "sold";
  gradient: string;
  emoji: string;
  niche_emoji: string;
  age_years: number;
  avg_views: number;
}

const RAW: Omit<Listing, "gradient"|"emoji"|"niche_emoji">[] = [
  // ─── TikTok ───────────────────────────────────────────────────────────────
  {
    id:"listing-0", platform:"TikTok", username:"@fitlife.daily", niche:"Fitness",
    followers:87000, monthly_income:420, engagement_rate:9.4, price:1800, minimum_offer:1400,
    status:"active", verified_income:true, tiktok_shop_eligible:true, monetized:true,
    location:"United States", age_years:2, avg_views:45000,
    description:"Clean fitness page, 87K loyal followers. Consistent 9%+ engagement. TikTok Shop enabled with active supplement affiliate links earning $200-400/mo. No violations ever. US audience 72%.",
    seller_name:"Carlos García", seller_country:"Spain", seller_flag:"🇪🇸", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-10T10:00:00Z", featured:true,
  },
  {
    id:"listing-1", platform:"TikTok", username:"@crypto.lens", niche:"Finance",
    followers:142000, monthly_income:780, engagement_rate:7.2, price:3200, minimum_offer:2600,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Arab Emirates", age_years:3, avg_views:72000,
    description:"Crypto and DeFi education content. 142K followers with strong 25-35 male demographic. Newsletter of 4,200 subscribers included. Exchange referral income $400-600/mo. UAE + UK + US traffic.",
    seller_name:"Omar Al-Qassim", seller_country:"UAE", seller_flag:"🇦🇪", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-05T09:00:00Z", featured:true,
  },
  {
    id:"listing-2", platform:"TikTok", username:"@glowby.sara", niche:"Beauty",
    followers:234000, monthly_income:1400, engagement_rate:11.8, price:4800, minimum_offer:3900,
    status:"active", verified_income:true, tiktok_shop_eligible:true, monetized:true,
    location:"United Kingdom", age_years:2, avg_views:120000,
    description:"Beauty and skincare mega-page. 234K followers, viral content history (3 videos over 2M views). TikTok Shop GMV averaging $1,800/mo. Active brand deal with UK skincare brand. Female 18-28 audience 84%.",
    seller_name:"Emma Dubois", seller_country:"France", seller_flag:"🇫🇷", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-08T08:00:00Z", featured:true,
  },
  {
    id:"listing-3", platform:"TikTok", username:"@gamezone.pk", niche:"Gaming",
    followers:56000, monthly_income:280, engagement_rate:8.9, price:950, minimum_offer:750,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:true,
    location:"Pakistan", age_years:1, avg_views:28000,
    description:"Mobile gaming content. 56K engaged followers. PUBG Mobile and Free Fire clips. Growing 3K followers/month consistently. Young male 16-24 audience 88%. Clean account, zero strikes.",
    seller_name:"Ahmed Malik", seller_country:"Pakistan", seller_flag:"🇵🇰", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-20T14:00:00Z", featured:false,
  },
  {
    id:"listing-4", platform:"TikTok", username:"@travel.with.kai", niche:"Travel",
    followers:98000, monthly_income:550, engagement_rate:6.8, price:2100, minimum_offer:1700,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Australia", age_years:2, avg_views:50000,
    description:"Luxury travel content creator. 98K followers. Hotel and airline brand deal history. Booking.com affiliate earning $300/mo. International audience — Australia, US, UK. 4 years of archived viral content.",
    seller_name:"Yuki Tanaka", seller_country:"Japan", seller_flag:"🇯🇵", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-12T11:00:00Z", featured:false,
  },
  {
    id:"listing-5", platform:"TikTok", username:"@chef.amara", niche:"Food",
    followers:178000, monthly_income:890, engagement_rate:10.3, price:3600, minimum_offer:2900,
    status:"active", verified_income:true, tiktok_shop_eligible:true, monetized:true,
    location:"Canada", age_years:3, avg_views:92000,
    description:"African-fusion recipe content. 178K followers with very high save rate. TikTok Shop kitchen equipment earning $400/mo. Meal kit sponsor deal for $600/mo. Female 25-40 audience. 2 viral videos over 5M views.",
    seller_name:"Amara Diallo", seller_country:"Senegal", seller_flag:"🇸🇳", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-03T09:00:00Z", featured:true,
  },
  {
    id:"listing-6", platform:"TikTok", username:"@tech.hans", niche:"Tech",
    followers:63000, monthly_income:340, engagement_rate:7.5, price:1350, minimum_offer:1050,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Germany", age_years:2, avg_views:31000,
    description:"Tech tips and gadget reviews. 63K followers. Amazon affiliate program earning $250/mo. Best Buy partnership history. Male 22-38 audience. German + US + UK traffic mix.",
    seller_name:"Lucas Müller", seller_country:"Germany", seller_flag:"🇩🇪", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-18T16:00:00Z", featured:false,
  },
  {
    id:"listing-7", platform:"TikTok", username:"@luxe.vibes", niche:"Lifestyle",
    followers:121000, monthly_income:680, engagement_rate:8.1, price:2700, minimum_offer:2200,
    status:"active", verified_income:false, tiktok_shop_eligible:true, monetized:true,
    location:"United Arab Emirates", age_years:2, avg_views:62000,
    description:"Luxury lifestyle content. 121K followers. TikTok Shop luxury accessory drops. Premium 25-40 demographic. UAE-based, strong GCC audience. Watch and fashion brand inquiry history.",
    seller_name:"Fatima Al-Zahra", seller_country:"Morocco", seller_flag:"🇲🇦", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-22T10:00:00Z", featured:false,
  },
  {
    id:"listing-8", platform:"TikTok", username:"@money.moves.ng", niche:"Finance",
    followers:205000, monthly_income:1150, engagement_rate:6.4, price:4200, minimum_offer:3400,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Nigeria", age_years:3, avg_views:105000,
    description:"Personal finance and investment content. 205K followers. Strong African diaspora audience. Fintech affiliate deals earning $700/mo. Growing 8K/month. Newsletter 6,500 subscribers included.",
    seller_name:"Kofi Mensah", seller_country:"Ghana", seller_flag:"🇬🇭", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-06T10:00:00Z", featured:true,
  },
  {
    id:"listing-9", platform:"TikTok", username:"@sports.radar", niche:"Sports",
    followers:312000, monthly_income:1600, engagement_rate:9.7, price:5500, minimum_offer:4400,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Brazil", age_years:3, avg_views:160000,
    description:"Sports highlights and predictions. 312K followers. Sportsbook sponsor deals $900/mo. Portuguese + Spanish + English content mix. World Cup content archive (massive engagement). Male 18-35 audience 91%.",
    seller_name:"Rafael Santos", seller_country:"Brazil", seller_flag:"🇧🇷", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-14T13:00:00Z", featured:false,
  },
  // ─── Instagram ───────────────────────────────────────────────────────────
  {
    id:"listing-10", platform:"Instagram", username:"@glow.journey", niche:"Beauty",
    followers:48000, monthly_income:380, engagement_rate:4.8, price:1600, minimum_offer:1300,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:4, avg_views:22000,
    description:"Beauty and skincare Instagram. 48K followers, 4.8% engagement — high for Instagram. Active brand deals with 2 skincare companies ($200/month combined). Clean aesthetic feed, professional photography. Female 22-34 US audience.",
    seller_name:"Priya Sharma", seller_country:"India", seller_flag:"🇮🇳", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-07T11:00:00Z", featured:true,
  },
  {
    id:"listing-11", platform:"Instagram", username:"@alpha.travel", niche:"Travel",
    followers:72000, monthly_income:520, engagement_rate:3.9, price:2200, minimum_offer:1800,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Germany", age_years:5, avg_views:34000,
    description:"Premium travel photography. 72K followers, consistent growth 2K/month. Hotel partnership history (Marriott, Hilton). Travel gear affiliate $300/mo. European + American audience split. 5-year archive of quality content.",
    seller_name:"Sofia Rossi", seller_country:"Italy", seller_flag:"🇮🇹", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-19T15:00:00Z", featured:false,
  },
  {
    id:"listing-12", platform:"Instagram", username:"@ironfitness.mx", niche:"Fitness",
    followers:156000, monthly_income:980, engagement_rate:5.2, price:3800, minimum_offer:3100,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Mexico", age_years:4, avg_views:74000,
    description:"Fitness and bodybuilding. 156K followers. Supplement brand deals (Optimum Nutrition, local brands) $600/mo. Male 20-35 Latin American audience. 3 active sponsorships. Gymshark Latin America inquiry received.",
    seller_name:"Isabella Morales", seller_country:"Mexico", seller_flag:"🇲🇽", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-02T08:00:00Z", featured:false,
  },
  {
    id:"listing-13", platform:"Instagram", username:"@paris.bites", niche:"Food",
    followers:34000, monthly_income:180, engagement_rate:6.1, price:720, minimum_offer:560,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"France", age_years:3, avg_views:16000,
    description:"Parisian food and restaurant reviews. 34K followers with very loyal community. Growing organically 1.5K/month. Strong local brand appeal — perfect for Paris restaurant or food brand. Female 28-45 audience.",
    seller_name:"Marie Leclerc", seller_country:"France", seller_flag:"🇫🇷", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-25T10:00:00Z", featured:false,
  },
  {
    id:"listing-14", platform:"Instagram", username:"@cryptobull.ae", niche:"Crypto",
    followers:28000, monthly_income:1400, engagement_rate:3.4, price:3200, minimum_offer:2600,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Arab Emirates", age_years:3, avg_views:13000,
    description:"Crypto investment analysis. 28K followers but very high-value — financial audience with avg income $120K+. Project sponsor deals $800-1200/post. Paid Substack newsletter 3,200 subscribers ($800/mo). Verified followers.",
    seller_name:"Nadia Hassan", seller_country:"Egypt", seller_flag:"🇪🇬", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-09T12:00:00Z", featured:false,
  },
  {
    id:"listing-15", platform:"Instagram", username:"@biz.mindset.co", niche:"Business",
    followers:89000, monthly_income:760, engagement_rate:4.6, price:2900, minimum_offer:2300,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:4, avg_views:42000,
    description:"Business and entrepreneurship content. 89K followers. Course funnel converting at 2.8% — $400/mo. SaaS tool affiliate deals $360/mo. Founder/exec audience. Very high DM engagement rate. Email list 7,200 included.",
    seller_name:"James Chen", seller_country:"Singapore", seller_flag:"🇸🇬", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-16T14:00:00Z", featured:false,
  },
  {
    id:"listing-16", platform:"Instagram", username:"@melody.finds", niche:"Music",
    followers:43000, monthly_income:220, engagement_rate:5.5, price:850, minimum_offer:680,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"United Kingdom", age_years:2, avg_views:20000,
    description:"Music discovery and artist spotlight. 43K followers. Strong 18-28 audience. Spotify affiliate potential. Music festival partnership opportunities. 5 years of content archived. Growing 2K/month organically.",
    seller_name:"Aisha Patel", seller_country:"United Kingdom", seller_flag:"🇬🇧", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-21T09:00:00Z", featured:false,
  },
  {
    id:"listing-17", platform:"Instagram", username:"@wellbeing.with.maya", niche:"Fitness",
    followers:67000, monthly_income:490, engagement_rate:4.9, price:1900, minimum_offer:1500,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Canada", age_years:3, avg_views:31000,
    description:"Yoga and holistic wellness. 67K followers. Lululemon ambassador (transferable). Calm app affiliate $240/mo. Online course $250/mo. Female 28-45 audience. Very loyal community with low unfollow rate.",
    seller_name:"Wei Liu", seller_country:"China", seller_flag:"🇨🇳", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-11T11:00:00Z", featured:false,
  },
  {
    id:"listing-18", platform:"Instagram", username:"@techreviewed.in", niche:"Tech",
    followers:52000, monthly_income:640, engagement_rate:4.1, price:2100, minimum_offer:1700,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"India", age_years:3, avg_views:24000,
    description:"Tech reviews and comparisons. 52K followers. Amazon Associates India $400/mo. Flipkart affiliate $240/mo. Male 20-35 Indian tech-savvy audience. 3 phone brand sponsorship history. Very high purchase intent traffic.",
    seller_name:"Rahul Verma", seller_country:"India", seller_flag:"🇮🇳", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-17T15:00:00Z", featured:false,
  },
  {
    id:"listing-19", platform:"Instagram", username:"@gamelife.br", niche:"Gaming",
    followers:38000, monthly_income:190, engagement_rate:5.7, price:680, minimum_offer:540,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"Brazil", age_years:2, avg_views:18000,
    description:"Gaming lifestyle and stream highlights. 38K followers. Growing 2K/month. Latin American gaming market (fastest growing globally). Male 16-26 audience. Strong community engagement. Perfect for gaming brand entry into Brazil.",
    seller_name:"Pedro Oliveira", seller_country:"Brazil", seller_flag:"🇧🇷", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-23T12:00:00Z", featured:false,
  },
  // ─── YouTube ─────────────────────────────────────────────────────────────
  {
    id:"listing-20", platform:"YouTube", username:"FitWithFatima", niche:"Fitness",
    followers:28000, monthly_income:560, engagement_rate:6.2, price:2200, minimum_offer:1800,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Kingdom", age_years:3, avg_views:18000,
    description:"Women's fitness channel. 28K subscribers. AdSense $320/mo. Supplement affiliate $240/mo. Every video gets 15K-25K views within 48 hours. Female 22-38 UK + US audience. Consistent upload schedule (2x/week for 3 years).",
    seller_name:"Fatima Al-Zahra", seller_country:"Morocco", seller_flag:"🇲🇦", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-06T10:00:00Z", featured:true,
  },
  {
    id:"listing-21", platform:"YouTube", username:"CryptoWithOmar", niche:"Finance",
    followers:45000, monthly_income:1800, engagement_rate:4.8, price:4200, minimum_offer:3400,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Arab Emirates", age_years:4, avg_views:28000,
    description:"DeFi and crypto investment channel. 45K subscribers. CPM $22+ (finance niche). AdSense $1,200/mo. Exchange sponsor deal $600/mo. Newsletter 8,000 subscribers included. Q4 seasonality doubles revenue. Male 25-40 global audience.",
    seller_name:"Omar Al-Qassim", seller_country:"UAE", seller_flag:"🇦🇪", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-04T09:00:00Z", featured:false,
  },
  {
    id:"listing-22", platform:"YouTube", username:"TechTalkDaily", niche:"Tech",
    followers:67000, monthly_income:1400, engagement_rate:5.4, price:3800, minimum_offer:3100,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:5, avg_views:42000,
    description:"Tech reviews and tutorials. 67K subscribers. AdSense CPM $18. Amazon Associates $400/mo. Laptop brand sponsorship history. Avg view duration 8.4 minutes — excellent watch time signal. Male 25-40 global audience.",
    seller_name:"Alex Thompson", seller_country:"Canada", seller_flag:"🇨🇦", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-13T11:00:00Z", featured:false,
  },
  {
    id:"listing-23", platform:"YouTube", username:"GamingWithPablo", niche:"Gaming",
    followers:22000, monthly_income:380, engagement_rate:7.1, price:1400, minimum_offer:1100,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:true,
    location:"Spain", age_years:2, avg_views:14000,
    description:"Spanish-language gaming content. 22K subscribers. AdSense $240/mo. Growing 1.5K subs/month. Spanish-speaking gaming market is underserved. Male 14-25 audience 86%. Perfect for brand wanting Hispanic market entry.",
    seller_name:"Carlos García", seller_country:"Spain", seller_flag:"🇪🇸", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-20T16:00:00Z", featured:false,
  },
  {
    id:"listing-24", platform:"YouTube", username:"KitchenStories.IN", niche:"Food",
    followers:112000, monthly_income:2200, engagement_rate:7.8, price:5800, minimum_offer:4700,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"India", age_years:6, avg_views:72000,
    description:"Indian cooking and recipe channel. 112K subscribers. AdSense $1,400/mo (CPM $12 food niche). Kitchen brand deals $800/mo. Flipkart affiliate $200/mo. Female 30-50 Indian + diaspora audience. 180+ videos evergreen library.",
    seller_name:"Priya Sharma", seller_country:"India", seller_flag:"🇮🇳", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-01T10:00:00Z", featured:false,
  },
  {
    id:"listing-25", platform:"YouTube", username:"WealthGrowth101", niche:"Finance",
    followers:33000, monthly_income:1100, engagement_rate:5.9, price:3600, minimum_offer:2900,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:3, avg_views:21000,
    description:"Personal finance and investing for beginners. 33K subscribers. CPM $24 (premium finance audience). Credit card affiliate $500/mo. Investment app referrals $360/mo. Email list 9,000 subscribers included. Growing 2K/month.",
    seller_name:"Marcus Johnson", seller_country:"United States", seller_flag:"🇺🇸", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-08T12:00:00Z", featured:false,
  },
  {
    id:"listing-26", platform:"YouTube", username:"WorldBehindLens", niche:"Travel",
    followers:54000, monthly_income:980, engagement_rate:5.1, price:2800, minimum_offer:2200,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Australia", age_years:4, avg_views:34000,
    description:"Travel documentary style channel. 54K subscribers. AdSense $600/mo. Booking.com partnership $380/mo. Evergreen destination content generating passive views years later. Male + Female 28-45 global audience.",
    seller_name:"Yuki Tanaka", seller_country:"Japan", seller_flag:"🇯🇵", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-15T13:00:00Z", featured:false,
  },
  {
    id:"listing-27", platform:"YouTube", username:"BeautyUnlocked", niche:"Beauty",
    followers:89000, monthly_income:1600, engagement_rate:6.5, price:4500, minimum_offer:3600,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:4, avg_views:56000,
    description:"Beauty tutorials and honest reviews. 89K subscribers. AdSense $900/mo (beauty CPM $10). Amazon storefront $500/mo. Sephora affiliate $200/mo. Female 18-35 US + UK audience 88%. Avg view duration 9.2 minutes.",
    seller_name:"Aisha Patel", seller_country:"United Kingdom", seller_flag:"🇬🇧", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-10T09:00:00Z", featured:false,
  },
  {
    id:"listing-28", platform:"YouTube", username:"SportsCentral.UK", niche:"Sports",
    followers:38000, monthly_income:720, engagement_rate:6.0, price:2100, minimum_offer:1700,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:true,
    location:"United Kingdom", age_years:3, avg_views:24000,
    description:"Premier League analysis and predictions. 38K subscribers. AdSense $420/mo. Sportsbook affiliate $300/mo. Peak revenue during football season. Male 20-40 UK + Europe audience. Very high comment engagement.",
    seller_name:"Jake Williams", seller_country:"United States", seller_flag:"🇺🇸", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-17T14:00:00Z", featured:false,
  },
  {
    id:"listing-29", platform:"YouTube", username:"MindfulLiving.JP", niche:"Lifestyle",
    followers:19000, monthly_income:420, engagement_rate:5.2, price:1600, minimum_offer:1300,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Japan", age_years:2, avg_views:12000,
    description:"Japanese minimalism and mindful living. 19K subscribers. Niche but very loyal audience. Calm app affiliate $180/mo. Online course $240/mo. Avg watch time 11 minutes. English subtitles on all videos — global appeal.",
    seller_name:"Yuki Tanaka", seller_country:"Japan", seller_flag:"🇯🇵", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-22T11:00:00Z", featured:false,
  },
  // ─── X (Twitter) ─────────────────────────────────────────────────────────
  {
    id:"listing-30", platform:"X", username:"@cryptosignals_x", niche:"Crypto",
    followers:42000, monthly_income:1600, engagement_rate:3.8, price:3800, minimum_offer:3100,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:false,
    location:"United States", age_years:5, avg_views:18000,
    description:"Verified crypto analyst account. 42K followers, X Premium subscription revenue. Paid newsletter 5,200 subscribers ($1,000/mo). Exchange affiliate deals $600/mo. High-trust authority in DeFi space. Male 25-40 professional audience.",
    seller_name:"Omar Al-Qassim", seller_country:"UAE", seller_flag:"🇦🇪", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-05T10:00:00Z", featured:false,
  },
  {
    id:"listing-31", platform:"X", username:"@techbreaking", niche:"Tech",
    followers:67000, monthly_income:520, engagement_rate:3.1, price:1800, minimum_offer:1450,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"United States", age_years:6, avg_views:28000,
    description:"Tech news and product leaks. 67K followers. Strong VC and founder network. Multiple publication relationships (exclusives). Newsletter 4,800 subscribers. X Premium subscription revenue. Authority in Silicon Valley circles.",
    seller_name:"Alex Thompson", seller_country:"Canada", seller_flag:"🇨🇦", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-19T15:00:00Z", featured:false,
  },
  {
    id:"listing-32", platform:"X", username:"@footy.insider", niche:"Sports",
    followers:89000, monthly_income:680, engagement_rate:4.5, price:2200, minimum_offer:1800,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"United Kingdom", age_years:4, avg_views:38000,
    description:"Football transfer news and scoops. 89K followers. Sportsbook affiliate $480/mo. Massive engagement during transfer windows and match days. Sponsored tweet history $200/post. Male 18-40 UK + global audience.",
    seller_name:"Marcus Johnson", seller_country:"United States", seller_flag:"🇺🇸", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-14T12:00:00Z", featured:false,
  },
  {
    id:"listing-33", platform:"X", username:"@financethread_x", niche:"Finance",
    followers:34000, monthly_income:1200, engagement_rate:4.2, price:3100, minimum_offer:2500,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:4, avg_views:14500,
    description:"Finance threads and stock picks. X Premium subscription revenue. Newsletter 4,200 subscribers ($800/mo). Credit card affiliate deals $400/mo. Very high-income audience (avg HHI $180K+). Most valuable demographic on X.",
    seller_name:"James Chen", seller_country:"Singapore", seller_flag:"🇸🇬", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-07T09:00:00Z", featured:false,
  },
  {
    id:"listing-34", platform:"X", username:"@gaming.leaks_x", niche:"Gaming",
    followers:28000, monthly_income:280, engagement_rate:5.8, price:750, minimum_offer:600,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"Canada", age_years:3, avg_views:12000,
    description:"Video game leaks and industry news. 28K engaged gaming enthusiasts. Strong relationships with game developers. Exclusive reveal opportunities. Growing 1.5K/month. Male 16-28 audience. Perfect for gaming brand or publisher.",
    seller_name:"Pedro Oliveira", seller_country:"Brazil", seller_flag:"🇧🇷", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-24T11:00:00Z", featured:false,
  },
  // ─── Telegram ─────────────────────────────────────────────────────────────
  {
    id:"listing-35", platform:"Telegram", username:"CryptoAlerts Pro", niche:"Crypto",
    followers:12000, monthly_income:2400, engagement_rate:14.0, price:3800, minimum_offer:3100,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Arab Emirates", age_years:3, avg_views:9600,
    description:"Premium crypto signals channel. 12K members, 800 paying subscribers at $18/mo = $14,400 MRR. VIP tier at $35/mo has 180 subs. Extremely profitable recurring revenue. 4 years of signal history (76% accuracy rate).",
    seller_name:"Nadia Hassan", seller_country:"Egypt", seller_flag:"🇪🇬", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-03T10:00:00Z", featured:false,
  },
  {
    id:"listing-36", platform:"Telegram", username:"TechNews Global", niche:"Tech",
    followers:28000, monthly_income:840, engagement_rate:8.8, price:2200, minimum_offer:1800,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"Germany", age_years:3, avg_views:22000,
    description:"Tech news Telegram channel. 28K members, 88% open rate. Sponsored post rate $300/post. German + English content. High purchasing power European audience. 3 posts/day consistent content schedule for 3 years.",
    seller_name:"Lucas Müller", seller_country:"Germany", seller_flag:"🇩🇪", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-20T09:00:00Z", featured:false,
  },
  {
    id:"listing-37", platform:"Telegram", username:"Finance Daily", niche:"Finance",
    followers:18000, monthly_income:1400, engagement_rate:10.2, price:3200, minimum_offer:2600,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Singapore", age_years:4, avg_views:14400,
    description:"Finance and investing Telegram. 18K members. Subscription model: $4,200 MRR (700 subs at $6/mo). Southeast Asian + global audience. Fintech affiliate deals $200/mo. Highly engaged professionals. Growing 800/month.",
    seller_name:"James Chen", seller_country:"Singapore", seller_flag:"🇸🇬", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-09T12:00:00Z", featured:false,
  },
  {
    id:"listing-38", platform:"Telegram", username:"Fitness Tips Daily", niche:"Fitness",
    followers:24000, monthly_income:480, engagement_rate:7.5, price:1200, minimum_offer:960,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"United States", age_years:2, avg_views:19000,
    description:"Daily fitness tips and workout plans. 24K members. Growing 1,200/month organically. Supplement affiliate potential $400-600/mo. Fitness app partnership opportunity. Very engaged community — high DM open rate.",
    seller_name:"Amara Diallo", seller_country:"Senegal", seller_flag:"🇸🇳", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-16T14:00:00Z", featured:false,
  },
  {
    id:"listing-39", platform:"Telegram", username:"Gaming Deals Hub", niche:"Gaming",
    followers:38000, monthly_income:1100, engagement_rate:11.8, price:2600, minimum_offer:2100,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:3, avg_views:30000,
    description:"Gaming deals and giveaways channel. 38K members. Sponsor deals $700/mo. Game key affiliate $400/mo. Very high engagement for deal channel. Growing 2K/month. Perfect for gaming company or affiliate marketer.",
    seller_name:"Rafael Santos", seller_country:"Brazil", seller_flag:"🇧🇷", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-13T10:00:00Z", featured:false,
  },
  // ─── Additional variety ───────────────────────────────────────────────────
  {
    id:"listing-40", platform:"TikTok", username:"@music.vibes.id", niche:"Music",
    followers:267000, monthly_income:1350, engagement_rate:12.8, price:4600, minimum_offer:3700,
    status:"active", verified_income:true, tiktok_shop_eligible:true, monetized:true,
    location:"Indonesia", age_years:2, avg_views:138000,
    description:"Music discovery and artist features. 267K followers. Indonesian + Southeast Asian audience. TikTok Shop music merchandise drops. Viral sound history — 3 sounds used 1M+ times. Record label interest for partnership.",
    seller_name:"Sari Wijaya", seller_country:"Indonesia", seller_flag:"🇮🇩", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-04T11:00:00Z", featured:false,
  },
  {
    id:"listing-41", platform:"Instagram", username:"@luxe.italia", niche:"Lifestyle",
    followers:94000, monthly_income:820, engagement_rate:5.1, price:3100, minimum_offer:2500,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Italy", age_years:5, avg_views:44000,
    description:"Italian luxury lifestyle and fashion. 94K followers. Versace and local Italian brand deal history. Shopping app affiliate $400/mo. Premium 28-45 female audience. European luxury market — very high CPM for fashion brands.",
    seller_name:"Sofia Rossi", seller_country:"Italy", seller_flag:"🇮🇹", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-06T09:00:00Z", featured:false,
  },
  {
    id:"listing-42", platform:"YouTube", username:"BusinessMindKorea", niche:"Business",
    followers:41000, monthly_income:1100, engagement_rate:5.8, price:3200, minimum_offer:2600,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"South Korea", age_years:4, avg_views:26000,
    description:"Business strategy channel (Korean + English). 41K subscribers. B2B SaaS sponsor deals $600/mo. Course sales $500/mo. Korean + English bilingual content opens two markets simultaneously. Growing 2.5K/month. Male 28-45 professional audience.",
    seller_name:"Jin-ho Park", seller_country:"South Korea", seller_flag:"🇰🇷", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-02T10:00:00Z", featured:false,
  },
  {
    id:"listing-43", platform:"TikTok", username:"@crypto.calls.ar", niche:"Crypto",
    followers:148000, monthly_income:960, engagement_rate:9.2, price:3900, minimum_offer:3200,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Saudi Arabia", age_years:2, avg_views:76000,
    description:"Arabic-language crypto content. 148K followers. Exchange affiliate deals $600/mo. Arabic-speaking crypto audience is massively underserved. Saudi + GCC + MENA market. Male 22-38 high-income demographic. Growing 10K/month.",
    seller_name:"Mohammed Al-Rashid", seller_country:"Saudi Arabia", seller_flag:"🇸🇦", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-18T13:00:00Z", featured:false,
  },
  {
    id:"listing-44", platform:"X", username:"@lifestyle.x_ae", niche:"Lifestyle",
    followers:22000, monthly_income:480, engagement_rate:4.9, price:1400, minimum_offer:1100,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"United Arab Emirates", age_years:3, avg_views:9500,
    description:"Luxury lifestyle on X. 22K followers, strong GCC audience. Watch and real estate sponsor potential. X Premium subscription revenue. High-net-worth individual demographic — among the most valuable audiences on any platform.",
    seller_name:"Sara Al-Khatib", seller_country:"Lebanon", seller_flag:"🇱🇧", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-21T11:00:00Z", featured:false,
  },
  {
    id:"listing-45", platform:"Telegram", username:"Sports Alerts ME", niche:"Sports",
    followers:52000, monthly_income:1600, engagement_rate:9.4, price:3400, minimum_offer:2800,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Kingdom", age_years:3, avg_views:41000,
    description:"Sports tips and match alerts. 52K members. Sportsbook sponsor $1,000/mo. Premium betting tips tier $600/mo (200 subscribers). Massive engagement during Champions League and Premier League. UK + MENA audience mix.",
    seller_name:"Kofi Mensah", seller_country:"Ghana", seller_flag:"🇬🇭", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-12T09:00:00Z", featured:false,
  },
  {
    id:"listing-46", platform:"Instagram", username:"@travel.diary.ae", niche:"Travel",
    followers:118000, monthly_income:980, engagement_rate:4.4, price:3600, minimum_offer:2900,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Arab Emirates", age_years:5, avg_views:56000,
    description:"Luxury travel photography. 118K followers. 3 active hotel brand deals (JW Marriott, Four Seasons). American Express travel affiliate $380/mo. Aspirational content, growing 3K/month. Arabic + English captions, global appeal.",
    seller_name:"Fatima Al-Zahra", seller_country:"Morocco", seller_flag:"🇲🇦", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-14T15:00:00Z", featured:false,
  },
  {
    id:"listing-47", platform:"YouTube", username:"MusicProducerAcademy", niche:"Music",
    followers:32000, monthly_income:760, engagement_rate:6.8, price:2400, minimum_offer:1900,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:3, avg_views:20000,
    description:"Music production tutorials. 32K subscribers. Ableton affiliate $400/mo. Course sales $360/mo. Native Instruments sponsor history. Music producer audience — high software purchase intent. Male 20-35 global audience.",
    seller_name:"Marcus Johnson", seller_country:"United States", seller_flag:"🇺🇸", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-08T10:00:00Z", featured:false,
  },
  {
    id:"listing-48", platform:"TikTok", username:"@kbeauty.trends", niche:"Beauty",
    followers:389000, monthly_income:2100, engagement_rate:10.6, price:7200, minimum_offer:5800,
    status:"active", verified_income:true, tiktok_shop_eligible:true, monetized:true,
    location:"South Korea", age_years:2, avg_views:200000,
    description:"K-beauty trends and tutorials. 389K followers, explosive growth (was 50K 12 months ago). TikTok Shop GMV averaging $1,400/mo. Korean beauty brand deal at $800/mo. Global female audience. Multiple viral videos 10M+ views.",
    seller_name:"Jin-ho Park", seller_country:"South Korea", seller_flag:"🇰🇷", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-05T09:00:00Z", featured:true,
  },

  // ─── Pinterest ────────────────────────────────────────────────────────────
  {
    id:"listing-50", platform:"Pinterest", username:"HomeDecorInspo", niche:"Lifestyle",
    followers:128000, monthly_income:480, engagement_rate:3.2, price:1900, minimum_offer:1500,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:5, avg_views:340000,
    description:"Home decor and interior design Pinterest. 128K followers, 340K monthly views. Amazon affiliate earning $300/mo. Home goods brand deal history (Wayfair). Female 28-45 US audience 82%. 1,200+ pins archived. Pinterest SEO optimized.",
    seller_name:"Emma Dubois", seller_country:"France", seller_flag:"🇫🇷", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-08T10:00:00Z", featured:false,
  },
  {
    id:"listing-51", platform:"Pinterest", username:"FitRecipesDaily", niche:"Food",
    followers:94000, monthly_income:380, engagement_rate:4.1, price:1500, minimum_offer:1200,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:4, avg_views:280000,
    description:"Healthy recipes and fitness meal prep. 94K followers. Amazon kitchen affiliate $240/mo. 8 million+ monthly impressions. 70% of pins rank on Google. Female 25-40 audience. Perfect for food delivery brand or kitchen equipment company.",
    seller_name:"Priya Sharma", seller_country:"India", seller_flag:"🇮🇳", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-15T09:00:00Z", featured:false,
  },
  {
    id:"listing-52", platform:"Pinterest", username:"LuxuryWeddingIdeas", niche:"Lifestyle",
    followers:212000, monthly_income:920, engagement_rate:5.8, price:3200, minimum_offer:2600,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Kingdom", age_years:6, avg_views:580000,
    description:"Luxury wedding planning and inspiration. 212K followers, 580K monthly views. Bridal brand affiliate $600/mo. Wedding venue affiliate $320/mo. Pinterest's highest-converting niche. Engaged female 24-35 audience. Evergreen pins bring traffic year-round.",
    seller_name:"Sofia Rossi", seller_country:"Italy", seller_flag:"🇮🇹", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-03T10:00:00Z", featured:true,
  },
  {
    id:"listing-53", platform:"Pinterest", username:"TechGadgetFinds", niche:"Tech",
    followers:67000, monthly_income:620, engagement_rate:3.9, price:2100, minimum_offer:1700,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Germany", age_years:3, avg_views:195000,
    description:"Tech gadgets and product reviews on Pinterest. 67K followers. Amazon Associates earning $480/mo + tech brand affiliate $140/mo. Male 25-40 global audience. Very high purchase intent — Pinterest users have 87% purchase intent. Ideal for electronics affiliate.",
    seller_name:"Lucas Müller", seller_country:"Germany", seller_flag:"🇩🇪", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-19T11:00:00Z", featured:false,
  },
  // ─── WeChat ───────────────────────────────────────────────────────────────
  {
    id:"listing-54", platform:"REMOVED", username:"FashionTrendsHK", niche:"Lifestyle",
    followers:45000, monthly_income:1800, engagement_rate:8.4, price:3600, minimum_offer:2900,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Hong Kong", age_years:4, avg_views:38000,
    description:"Luxury fashion WeChat Official Account. 45K followers. Brand deal income from LVMH-group brands $1,200/mo. Mini-program store revenue $600/mo. Hong Kong + Mainland China audience. High-net-worth female 28-42 demographic. WeChat monetization fully unlocked.",
    seller_name:"Wei Liu", seller_country:"China", seller_flag:"🇨🇳", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-06T09:00:00Z", featured:true,
  },
  {
    id:"listing-55", platform:"REMOVED", username:"InvestmentPro.CN", niche:"Finance",
    followers:28000, monthly_income:2400, engagement_rate:11.2, price:4800, minimum_offer:3900,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"China", age_years:5, avg_views:24000,
    description:"Premium investment and finance Official Account. 28K subscribers. Paid subscription revenue $1,600/mo. Financial product affiliate deals $800/mo. Mainland China professional investor audience (avg portfolio $500K+). Most valuable demographic on Chinese internet.",
    seller_name:"Jin-ho Park", seller_country:"South Korea", seller_flag:"🇰🇷", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-10T12:00:00Z", featured:false,
  },
  {
    id:"listing-56", platform:"REMOVED", username:"FoodLifestyleSH", niche:"Food",
    followers:62000, monthly_income:1100, engagement_rate:7.8, price:2200, minimum_offer:1800,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"China", age_years:3, avg_views:52000,
    description:"Shanghai food and lifestyle Official Account. 62K followers. Restaurant sponsorships $700/mo. Food delivery affiliate $400/mo. Urban China 25-38 audience. Mini-program integration ready. Growing 2K/month consistently.",
    seller_name:"Sari Wijaya", seller_country:"Indonesia", seller_flag:"🇮🇩", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-16T14:00:00Z", featured:false,
  },
  {
    id:"listing-57", platform:"REMOVED", username:"TravelChinaGuide", niche:"Travel",
    followers:38000, monthly_income:860, engagement_rate:6.9, price:1700, minimum_offer:1400,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:true,
    location:"China", age_years:4, avg_views:32000,
    description:"China travel guide for international visitors and Chinese diaspora. 38K followers. Hotel affiliate deals $600/mo. Tour operator partnerships $260/mo. Bilingual English/Chinese content. Perfect for travel brand wanting China market entry.",
    seller_name:"Yuki Tanaka", seller_country:"Japan", seller_flag:"🇯🇵", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-21T10:00:00Z", featured:false,
  },
  // ─── LinkedIn ─────────────────────────────────────────────────────────────
  {
    id:"listing-58", platform:"REMOVED", username:"SarahChenCMO", niche:"Business",
    followers:48000, monthly_income:1200, engagement_rate:4.8, price:3800, minimum_offer:3100,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:5, avg_views:180000,
    description:"CMO and marketing executive LinkedIn presence. 48K followers. B2B SaaS sponsor deals $800/mo. Online course revenue $400/mo. C-suite and VP-level audience — avg salary $180K+. Newsletter 6,200 subscribers. LinkedIn's highest CPM demographic.",
    seller_name:"James Chen", seller_country:"Singapore", seller_flag:"🇸🇬", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-05T10:00:00Z", featured:false,
  },
  {
    id:"listing-59", platform:"REMOVED", username:"StartupFounderDaily", niche:"Business",
    followers:92000, monthly_income:1800, engagement_rate:6.2, price:5200, minimum_offer:4200,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:4, avg_views:420000,
    description:"Startup and entrepreneurship content. 92K followers. Top Voice badge. SaaS tool affiliate $1,000/mo. Course revenue $800/mo. Founder and investor audience. Posts consistently reach 100K+ impressions. Newsletter 18,000 subscribers included.",
    seller_name:"Marcus Johnson", seller_country:"United States", seller_flag:"🇺🇸", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-02T09:00:00Z", featured:true,
  },
  {
    id:"listing-60", platform:"REMOVED", username:"AIProductInsights", niche:"Tech",
    followers:34000, monthly_income:1400, engagement_rate:5.4, price:4100, minimum_offer:3300,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Kingdom", age_years:3, avg_views:156000,
    description:"AI and product management insights. 34K followers. AI tool sponsor deals $900/mo. Newsletter 8,500 subscribers ($500/mo). Tech exec and PM audience — extremely high-value B2B demographic. Growing 3K/month. Perfect for AI company brand building.",
    seller_name:"Aisha Patel", seller_country:"United Kingdom", seller_flag:"🇬🇧", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-13T11:00:00Z", featured:false,
  },
  {
    id:"listing-61", platform:"REMOVED", username:"FinanceCareerPro", niche:"Finance",
    followers:67000, monthly_income:980, engagement_rate:4.1, price:2900, minimum_offer:2300,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Arab Emirates", age_years:4, avg_views:290000,
    description:"Finance career and investment banking LinkedIn. 67K followers. CFA prep course affiliate $600/mo. Financial recruiter partnerships $380/mo. Finance professional audience globally. Strong MENA and US presence. Top Voice in Finance.",
    seller_name:"Nadia Hassan", seller_country:"Egypt", seller_flag:"🇪🇬", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-17T15:00:00Z", featured:false,
  },
  // ─── Snapchat ─────────────────────────────────────────────────────────────
  {
    id:"listing-62", platform:"Snapchat", username:"@streetfashion.snap", niche:"Lifestyle",
    followers:82000, monthly_income:520, engagement_rate:9.8, price:1600, minimum_offer:1300,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:3, avg_views:68000,
    description:"Street fashion and style Snapchat. 82K subscribers. Brand deal with fashion brand $400/mo. Snap Star monetization $120/mo. Young 16-25 Gen Z audience — highest spending power growth demo. Strong daily story views. Ideal for clothing or lifestyle brand.",
    seller_name:"Carlos García", seller_country:"Spain", seller_flag:"🇪🇸", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-09T10:00:00Z", featured:false,
  },
  {
    id:"listing-63", platform:"Snapchat", username:"@gamingwithkev", niche:"Gaming",
    followers:124000, monthly_income:680, engagement_rate:11.4, price:2100, minimum_offer:1700,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:true,
    location:"United States", age_years:4, avg_views:104000,
    description:"Gaming and entertainment Snapchat. 124K subscribers. Snap Star status. Gaming brand partnerships $500/mo. Snap+ subscription revenue $180/mo. Male 15-24 audience 88%. Very high daily engagement. Discover show partnership potential.",
    seller_name:"Pedro Oliveira", seller_country:"Brazil", seller_flag:"🇧🇷", seller_id:"user-5", seller_rating:4.9, seller_sales:11,
    created_at:"2025-01-20T13:00:00Z", featured:false,
  },
  {
    id:"listing-64", platform:"Snapchat", username:"@beautybysara.ae", niche:"Beauty",
    followers:58000, monthly_income:440, engagement_rate:8.6, price:1400, minimum_offer:1100,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"United Arab Emirates", age_years:2, avg_views:48000,
    description:"Arabic beauty and makeup Snapchat. 58K subscribers. UAE + GCC female audience. Beauty brand deal $360/mo. Snap Star monetization $80/mo. Arabic-language beauty content highly underserved on Snapchat. Massive regional growth potential.",
    seller_name:"Sara Al-Khatib", seller_country:"Lebanon", seller_flag:"🇱🇧", seller_id:"user-3", seller_rating:4.8, seller_sales:5,
    created_at:"2025-01-24T09:00:00Z", featured:false,
  },
  // ─── Threads ──────────────────────────────────────────────────────────────
  {
    id:"listing-65", platform:"Threads", username:"@cryptothreads", niche:"Crypto",
    followers:34000, monthly_income:580, engagement_rate:7.2, price:1400, minimum_offer:1100,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"United States", age_years:1, avg_views:14000,
    description:"Crypto commentary and analysis on Threads. 34K followers, fast-growing (was 5K 6 months ago). Exchange affiliate deals $400/mo. Threads is the fastest-growing platform of 2024-2025. Early mover advantage — get in before competition explodes. Tech-savvy 22-35 audience.",
    seller_name:"Omar Al-Qassim", seller_country:"UAE", seller_flag:"🇦🇪", seller_id:"user-4", seller_rating:4.6, seller_sales:2,
    created_at:"2025-01-22T10:00:00Z", featured:false,
  },
  {
    id:"listing-66", platform:"Threads", username:"@businessthreads", niche:"Business",
    followers:67000, monthly_income:760, engagement_rate:8.8, price:2200, minimum_offer:1800,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:false,
    location:"United States", age_years:1, avg_views:28000,
    description:"Business and entrepreneurship content. 67K followers — one of the largest business accounts on Threads. SaaS affiliate deals $560/mo. Course sales $200/mo. Meta-integrated — cross-posts to Instagram automatically. Growing 8K/month. Early-mover premium account.",
    seller_name:"Kofi Mensah", seller_country:"Ghana", seller_flag:"🇬🇭", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-11T12:00:00Z", featured:false,
  },
  {
    id:"listing-67", platform:"Threads", username:"@fitthreads.daily", niche:"Fitness",
    followers:48000, monthly_income:340, engagement_rate:9.4, price:950, minimum_offer:760,
    status:"active", verified_income:false, tiktok_shop_eligible:false, monetized:false,
    location:"United States", age_years:1, avg_views:20000,
    description:"Fitness motivation and workout content. 48K followers. Supplement affiliate $340/mo. Linked to 48K Instagram followers (same Meta account). Threads algorithm currently very favorable — high organic reach. Growing 4K/month. Clean account, zero violations.",
    seller_name:"Isabella Morales", seller_country:"Mexico", seller_flag:"🇲🇽", seller_id:"user-2", seller_rating:5.0, seller_sales:14,
    created_at:"2025-01-25T11:00:00Z", featured:false,
  },
  {
    id:"listing-49", platform:"Instagram", username:"@biz.africa", niche:"Business",
    followers:76000, monthly_income:580, engagement_rate:5.3, price:2100, minimum_offer:1700,
    status:"active", verified_income:true, tiktok_shop_eligible:false, monetized:true,
    location:"Nigeria", age_years:3, avg_views:36000,
    description:"Business and entrepreneurship for African market. 76K followers. African fintech affiliate deals $380/mo. Course sales $200/mo. Nigerian + pan-African audience. Fastest growing economic market in the world. Growing 4K/month.",
    seller_name:"Amara Diallo", seller_country:"Senegal", seller_flag:"🇸🇳", seller_id:"user-1", seller_rating:4.9, seller_sales:8,
    created_at:"2025-01-11T10:00:00Z", featured:false,
  },
];

export const SEED_LISTINGS: Listing[] = RAW.filter((l) => !["WeChat","LinkedIn","Discord"].includes(l.platform)).map((l) => ({
  ...l,
  isSeed: true,
  listingStatus: "pending_verification" as const,
  gradient:    PLATFORM_GRADIENTS[l.platform] || "#6366f1",
  emoji:       PLATFORM_EMOJIS[l.platform]    || "📱",
  niche_emoji: NICHE_EMOJIS[l.niche]          || "✨",
})).sort((a, b) => {
  // 1. Real listings (non-seed, from DB) always first
  if (!a.isSeed && b.isSeed) return -1;
  if (a.isSeed && !b.isSeed) return 1;
  // 2. Among real listings: newest first (by created_at)
  if (!a.isSeed && !b.isSeed) {
    return new Date(b.created_at).getTime() - new Date(a.created_at).getTime();
  }
  // 3. Among seed listings: featured first, then by price desc
  if (a.featured && !b.featured) return -1;
  if (!a.featured && b.featured) return 1;
  return b.price - a.price;
});

export const MARKETPLACE_STATS = {
  active_listings: 5214,
  total_volume:    14_200_000,
  avg_rating:      4.98,
  total_transfers: 3842,
};
